# board
spring:
  jpa:
    database: POSTGRESQL 
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/board
    username: board
    password: password
  database:
    driverClassName: org.postgresql.Driver